version: "3"
services:
  mysql:
    image: "mysql:8.0"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
    - "MYSQL_DATABASE=apparatus"
    - "MYSQL_USER_FILE=/run/secrets/mysql-apparatus-user"
    - "MYSQL_PASSWORD_FILE=/run/secrets/mysql-apparatus-password"
    - "MYSQL_RANDOM_ROOT_PASSWORD=1"
    volumes:
    - "dbdata:/var/lib/mysql"
    - "${APPARATUS_SECRETS_DIR}/mysql:/run/secrets:ro"
    restart: "on-failure"
  nginx:
    volumes:
    - "./env/ssl:/etc/letsencrypt:ro"
  certbot:
    entrypoint: "true"
volumes:
  dbdata:
