version: "3"
services:
  mysql:
    image: "mysql:8.0"
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
    - "3306:3306"
    environment:
    - "MYSQL_DATABASE=apparatus"
    - "MYSQL_USER_FILE=/run/secrets/mysql-apparatus-user"
    - "MYSQL_PASSWORD_FILE=/run/secrets/mysql-apparatus-password"
    - "MYSQL_RANDOM_ROOT_PASSWORD=1"
    volumes:
    - "dbdata:/var/lib/mysql"
  web:
    image: "jasujm/apparatus-web"
    ports:
    - "8000:8000"
    environment:
    - "ENV_PATH=/run/secrets/web-envfile"
    - "DATA_DIR=/var/www/apparatus"
    depends_on:
    - "mysql"
    volumes:
    - "webdata:/var/www/apparatus"
  nginx:
    image: "jasujm/apparatus-nginx"
    command: >-
      /bin/bash -c "write-apparatus-conf.sh;
      trap 'kill $$(jobs -p)' EXIT;
      while :; do
        sleep 1d;
        nginx -s reload;
      done &
      nginx -g 'daemon off;'"
    ports:
    - "80:80"
    - "443:443"
    environment:
    - "SERVER_NAME=localhost"
    volumes:
    - "webdata:/var/www/apparatus:ro"
    depends_on:
    - "web"
volumes:
  dbdata:
  webdata:
