version: "3"
services:
  apparatus:
    image: "jasujm/apparatus"
    build: "."
    environment:
    - "ENV_PATH=/run/secrets/envfile"
    - "DATA_DIR=/var/www/apparatus"
    - "ALLOWED_HOSTS=127.0.0.1,::,localhost,www.${APPARATUS_SERVER_NAME}"
    volumes:
    - "webdata:/var/www/apparatus"
    - "${APPARATUS_SECRETS_DIR}/apparatus:/run/secrets:ro"
    restart: "on-failure"
  nginx:
    image: "nginx:1.23"
    command: >-
      /bin/bash -c "trap 'kill $$(jobs -p)' EXIT;
      while :; do
        sleep 1d;
        nginx -s reload;
      done &
      nginx -g 'daemon off;'"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "webdata:/var/www/apparatus:ro"
    - "./nginx/inc.d:/etc/nginx/inc.d:ro"
    - "${APPARATUS_NGINX_CONF_DIR}:/etc/nginx/conf.d:ro"
    - "certbotetc:/etc/letsencrypt:ro"
    - "certbotwww:/var/www/certbot:ro"
    restart: "on-failure"
  certbot:
    image: "certbot/certbot"
    entrypoint: >-
      /bin/sh -c "trap exit TERM;
      while :;
        do certbot renew;
        sleep 1d;
      done;"
    volumes:
    - "certbotetc:/etc/letsencrypt"
    - "certbotwww:/var/www/certbot"
    depends_on:
    - "nginx"
    restart: "on-failure"
volumes:
  webdata:
  certbotetc:
  certbotwww:
