version: "3"
services:
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 1d; done;'"
    volumes:
    - "certbotetc:/etc/letsencrypt"
    - "certbotwww:/var/www/certbot"
    depends_on:
    - "nginx"
  nginx:
    volumes:
    - "certbotetc:/etc/letsencrypt:ro"
    - "certbotwww:/var/www/certbot:ro"
volumes:
  certbotetc:
  certbotwww:
