# Generated by Django 2.2.9 on 2020-01-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apparatus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programminglanguage",
            name="is_external",
            field=models.BooleanField(
                default=False, verbose_name="Is external resource"
            ),
        ),
        migrations.AddField(
            model_name="programminglanguage",
            name="subresource_integrity_hash",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Subresource integrity hash"
            ),
        ),
    ]
