# Generated by Django 2.2.11 on 2020-03-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apparatus", "0002_auto_20200119_2102"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codesnippet",
            options={
                "verbose_name": "code snippet",
                "verbose_name_plural": "code snippets",
            },
        ),
        migrations.AlterModelOptions(
            name="programminglanguage",
            options={
                "verbose_name": "programming language",
                "verbose_name_plural": "programming languages",
            },
        ),
        migrations.RemoveField(model_name="programminglanguage", name="is_external",),
        migrations.RemoveField(
            model_name="programminglanguage", name="subresource_integrity_hash",
        ),
    ]
