# Generated by Django 2.2.12 on 2020-04-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("apparatus", "0003_auto_20200321_0700"),
    ]

    operations = [
        migrations.CreateModel(
            name="FalsePositiveDemo",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="apparatus_falsepositivedemo",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("prevalence", models.FloatField(verbose_name="Prevalence")),
                ("sensitivity", models.FloatField(verbose_name="Sensitivity")),
                ("specificity", models.FloatField(verbose_name="Specificity")),
            ],
            options={
                "verbose_name": "false positives demo",
                "verbose_name_plural": "false positives demos",
            },
            bases=("cms.cmsplugin",),
        ),
    ]
